import { AICapability, Domain } from "../types/assessment";

// ─── Capability detection ────────────────────────────────────────────────────

const CAPABILITY_KEYWORDS: Record<AICapability, string[]> = {
  natural_language_generation: [
    "chat",
    "chatbot",
    "conversation",
    "conversational",
    "agent",
    "assistant",
    "gpt",
    "llm",
    "language model",
    "nlp",
    "text",
    "write",
    "writing",
    "draft",
    "summarise",
    "summarize",
    "summarization",
    "generate text",
    "content",
    "coach",
    "coaching",
    "advice",
    "guidance",
    "respond",
    "response",
    "answer",
    "q&a",
    "qa",
    "question",
    "explain",
    "feedback",
  ],
  image_video_generation: [
    "image",
    "photo",
    "picture",
    "video",
    "audio",
    "visual",
    "generate image",
    "stable diffusion",
    "midjourney",
    "dall-e",
    "synthetic media",
    "deepfake",
    "avatar",
    "render",
    "illustration",
  ],
  decision_making: [
    "decision",
    "approve",
    "reject",
    "automate",
    "automation",
    "workflow",
    "triage",
    "flag",
    "action",
    "introduce",
    "introduction",
    "match",
    "matching",
    "connect",
    "connects",
    "route",
    "routing",
    "assign",
    "allocate",
    "hire",
    "hiring",
    "shortlist",
    "select",
    "selection",
  ],
  scoring_ranking: [
    "score",
    "scoring",
    "rank",
    "ranking",
    "rate",
    "rating",
    "prioritise",
    "prioritize",
    "priorit",
    "cv",
    "resume",
    "candidate",
    "applicant",
    "credit",
    "risk",
    "screen",
    "screening",
    "evaluate",
    "evaluation",
    "assess",
    "assessment",
    "grade",
    "grading",
  ],
  biometric_recognition: [
    "face",
    "facial",
    "biometric",
    "fingerprint",
    "voice recognition",
    "speaker",
    "identity verification",
    "liveness",
    "authenticate",
    "id check",
  ],
  emotion_detection: [
    "emotion",
    "sentiment",
    "mood",
    "stress",
    "mental state",
    "feeling",
    "affect",
    "wellbeing",
    "engagement",
    "attention",
  ],
  classification: [
    "classif",
    "categor",
    "label",
    "tag",
    "sort",
    "filter",
    "moderate",
    "moderation",
    "detect",
    "detection",
    "identify",
    "identification",
    "flag content",
    "spam",
    "fraud detection",
  ],
  recommendation: [
    "recommend",
    "recommendation",
    "suggest",
    "suggestion",
    "personalise",
    "personalize",
    "personalised",
    "personalized",
    "feed",
    "curate",
    "job",
    "jobs",
    "career",
    "opportunity",
    "opportunities",
    "search",
    "find",
    "discover",
    "match",
    "connect",
  ],
  prediction: [
    "predict",
    "prediction",
    "forecast",
    "churn",
    "anomaly",
    "detect risk",
    "early warning",
    "likely to",
    "probability",
    "propensity",
  ],
  translation: [
    "translat",
    "translation",
    "multilingual",
    "language barrier",
    "localise",
    "localize",
  ],
  other: [],
};

export function detectCapabilities(text: string): AICapability[] {
  const lower = text.toLowerCase();
  return (Object.entries(CAPABILITY_KEYWORDS) as [AICapability, string[]][])
    .filter(
      ([cap, keywords]) =>
        cap !== "other" && keywords.some((kw) => lower.includes(kw)),
    )
    .map(([cap]) => cap);
}

// ─── Domain detection ────────────────────────────────────────────────────────

const DOMAIN_KEYWORDS: Record<Domain, string[]> = {
  employment: [
    "job",
    "jobs",
    "career",
    "careers",
    "recruit",
    "recruitment",
    "hire",
    "hiring",
    "interview",
    "interviews",
    "candidate",
    "applicant",
    "cv",
    "resume",
    "workforce",
    "employee",
    "employer",
    "hr ",
    "human resource",
    "talent",
    "staffing",
    "hiring manager",
    "payroll",
    "onboard",
  ],
  education: [
    "student",
    "school",
    "university",
    "college",
    "learn",
    "learning",
    "course",
    "curriculum",
    "tutor",
    "tutoring",
    "grade",
    "exam",
    "educat",
    "classroom",
    "teacher",
    "academic",
    "admission",
  ],
  healthcare: [
    "health",
    "healthcare",
    "medical",
    "patient",
    "clinical",
    "diagnos",
    "treatment",
    "hospital",
    "doctor",
    "therapy",
    "drug",
    "pharma",
    "symptom",
    "wellbeing",
    "mental health",
    "care",
  ],
  essential_services: [
    "credit",
    "loan",
    "mortgage",
    "insurance",
    "bank",
    "financial",
    "benefit",
    "welfare",
    "housing",
    "utility",
    "social service",
  ],
  biometrics_identity: [
    "biometric",
    "facial recognition",
    "fingerprint",
    "identity",
    "id verification",
    "kyc",
    "know your customer", // "authentication",
  ],
  critical_infrastructure: [
    "energy",
    "power grid",
    "water",
    "transport network",
    "railway",
    "airport",
    "nuclear",
    "infrastructure",
    "utility network",
    "telecom",
  ],
  law_enforcement: [
    "police",
    "law enforcement",
    "crime",
    "criminal",
    "surveillance",
    "security agency",
    "border force",
    "investigation",
  ],
  migration_asylum: [
    "migration",
    "immigrant",
    "asylum",
    "refugee",
    "border",
    "visa",
    "passport",
    "nationality",
    "citizenship",
  ],
  justice_democracy: [
    "court",
    "judge",
    "legal",
    "justice",
    "election",
    "vote",
    "voting",
    "democracy",
    "parliament",
    "sentencing",
    "litigation",
  ],
  transportation: [
    "transport",
    "autonomous vehicle",
    "self-driving",
    "traffic",
    "logistics",
    "delivery",
    "fleet",
    "aviation",
    "drone",
  ],
  general_business: [
    "crm",
    "analytics",
    "productivity",
    "operations",
    "internal tool",
    "sales",
    "marketing",
    "customer service",
    "support",
    "erp",
  ],
  creative_entertainment: [
    "creative",
    "entertainment",
    "gaming",
    "game",
    "music",
    "art",
    "media",
    "film",
    "content creator",
    "influencer",
    "social media",
  ],
  other: [],
};

export function detectDomain(text: string): Domain | null {
  const lower = text.toLowerCase();
  // Score each domain by how many keywords match
  const scores = (Object.entries(DOMAIN_KEYWORDS) as [Domain, string[]][])
    .filter(([d]) => d !== "other")
    .map(([domain, keywords]) => ({
      domain,
      score: keywords.filter((kw) => lower.includes(kw)).length,
    }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score);

  return scores[0]?.domain ?? null;
}
